spring:
  application:
    name : springbootZuul
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml

server:
  port : 8008

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springbootService2