server:
  port: 8002
spring :
  application:
    name: springbootService2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/

# 默认之配置为TM的本机默认端口
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  # 开启日志,默认为false
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    level.com.codingapi.txlcn: DEBUG