server:
  port: 8040

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: springbootConsumerFeign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml